apiVersion: v1
kind: Service
metadata:
  name: max-speech-to-text-converter
spec:
  selector:
    app: max-speech-to-text-converter
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-speech-to-text-converter
  labels:
    app: max-speech-to-text-converter
spec:
  selector:
    matchLabels:
      app: max-speech-to-text-converter
  replicas: 1
  template:
    metadata:
      labels:
        app: max-speech-to-text-converter
    spec:
      containers:
      - name: max-speech-to-text-converter
        image: codait/max-speech-to-text-converter:latest
        ports:
          - containerPort: 5000
